#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["aiohttp"]
# ///
"""Pollinations.ai — zero-auth AI image generation fallback."""

import sys
import urllib.parse

import aiohttp

sys.path.insert(0, str(__import__("pathlib").Path(__file__).parent.parent))
from _well_utils import ImageResult, warn
from sources.base import ImageSource


class PollinationsSource(ImageSource):
    name = "pollinations"
    display_name = "Pollinations AI"
    tier = 3
    requires_key = False
    rate_limit_seconds = 1.0
    base_url = "https://image.pollinations.ai"

    async def search(
        self,
        query: str,
        limit: int,
        license_filter: str | None,
        session: aiohttp.ClientSession,
    ) -> list[ImageResult]:
        # Pollinations generates images from prompts, not search.
        # Return a single generated image URL for the query.
        await self._rate_wait()

        encoded_prompt = urllib.parse.quote(query)
        results: list[ImageResult] = []

        # Generate up to limit images with different seeds
        for seed in range(min(limit, 3)):
            img_url = f"{self.base_url}/prompt/{encoded_prompt}?width=1024&height=1024&seed={seed}&nologo=true"

            # Verify the URL is reachable (HEAD request)
            try:
                async with session.head(
                    img_url, timeout=aiohttp.ClientTimeout(total=10),
                    allow_redirects=True,
                ) as resp:
                    if resp.status != 200:
                        continue
            except (aiohttp.ClientError, TimeoutError):
                if seed == 0:
                    warn("pollinations: service unreachable")
                    return []
                continue

            results.append(ImageResult(
                source="pollinations",
                title=f"AI: {query[:50]}",
                url=img_url,
                thumbnail_url=img_url,
                license="Free Use",
                attribution="Generated by Pollinations.ai",
                width=1024,
                height=1024,
                tags=["ai-generated"],
                source_url="https://pollinations.ai",
            ))

        return results
