export const MDB_STANDARD = {
  code: "Q/SY XJ 0222-2009",
  confirmation: "2014年11月确认",
  title: "录井数据库逻辑结构",
  tables: [
    ["AJLJ01", "完井基础数据"],
    ["AJLJ02", "岩屑分段描述"],
    ["AJLJ03", "岩屑含量荧光数据"],
    ["AJLJ04", "钻井取心统计"],
    ["AJLJ04_1", "岩心出筒油气水描述"],
    ["AJLJ05", "岩心描述"],
    ["AJLJ06", "井壁取心描述"],
    ["AJLJ07", "气测及钻井液简易性能数据"],
    ["AJLJ09", "钻井液简易性能分段数据"],
    ["AJLJ10", "油气水浸基础数据"],
    ["AJLJ10_1", "油气水浸测量数据"],
    ["AJLJ11", "井涌基础数据"],
    ["AJLJ11_1", "井涌测量数据"],
    ["AJLJ12", "气测后效基础数据"],
    ["AJLJ12_1", "气测后效测量数据"],
    ["AJLJ14", "钻井液全脱气数据"],
    ["AJLJ15", "气测解释数据"],
    ["AJLJ16", "井喷记录数据"],
    ["AJLJ17", "井漏记录数据"],
    ["AJLJ18", "孔渗分析数据"],
    ["AJLJ19", "储层热解分析数据"],
    ["AJLJ20", "储层热解解释数据"],
    ["AJLJ21", "生油岩热解分析数据"],
    ["AJLJ22", "生油层热解解释数据"],
    ["AJLJ23", "碳酸盐测定数据"],
    ["AJLJ24", "泥岩密度测定数据"],
    ["AJLJ25", "地层分层数据"],
    ["AJLJ26", "地层压力解释数据"],
    ["AJLJ27", "录井综合解释数据"],
    ["AJLJ29", "油气显示统计"],
    ["AJLJ30", "综合解释统计"],
    ["AJLJ31", "井史记录数据"],
    ["AJLJ38", "录井工程参数数据"],
    ["AJLJ42", "荧光定量分析数据"],
    ["AJLJ43", "油层浸泡时间统计"],
    ["AJLJ62", "断层描述数据"],
    ["AJLJ63", "录井项目统计"],
    ["AJLJ64", "完井地质总结报告管理"],
    ["AJLJ64_1", "完井地质总结报告附件管理"],
  ] as const,
  basicTable: {
    standardName: "AJLJ01",
    observedAlias: "ADLJ01",
    requiredColumns: ["JH", "JHDM", "SGDW", "SGDH", "LJDW", "KZRQ", "WZRQ", "BXG", "WZJS"] as const,
  },
} as const

export function observedTableName(standardName: string) {
  return standardName.replace(/^AJLJ/, "ADLJ")
}
